<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PricesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('prices')->truncate();
        // DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        DB::table('prices')->insert([
            [
                'product_id'     => 1, 
                'amount'         => 11.11,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 50000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 2, 
                'amount'         => 100.00,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 450000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 3, 
                'amount'         => 142.00,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 640000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 4, 
                'amount'         => 143.33,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 420000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 5, 
                'amount'         => 24.44,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 110000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 6, 
                'amount'         => 28.88,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 130000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 7, 
                'amount'         => 122.22,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 550000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 8, 
                'amount'         => 15.55,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 70000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 9, 
                'amount'         => 55.55,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 250000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 10, 
                'amount'         => 20.00,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 90000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 11, 
                'amount'         => 20.00,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 90000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 12, 
                'amount'         => 144.44,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 650000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 13, 
                'amount'         => 6.66,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 30000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 14, 
                'amount'         => 35.55,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 160000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 15, 
                'amount'         => 13.33,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 60000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 16, 
                'amount'         => 155.55,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 700000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 17, 
                'amount'         => 64.44,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 290000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 18, 
                'amount'         => 177.77,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 800000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 19, 
                'amount'         => 177.77,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 800000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 20, 
                'amount'         => 41.11,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 185000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 21, 
                'amount'         => 115.55,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 520000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 22, 
                'amount'         => 22.22,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 100000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 23, 
                'amount'         => 133.33,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 600000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 24, 
                'amount'         => 155.55,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 700000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 25, 
                'amount'         => 64.44,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 290000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 26, 
                'amount'         => 60.00,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 270000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 27, 
                'amount'         => 53.33,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 240000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 28, 
                'amount'         => 26.66,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 120000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 29, 
                'amount'         => 71.11,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 320000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 30, 
                'amount'         => 26.66,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 120000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'product_id'     => 31, 
                'amount'         => 26.66,
                'type'           => 'regular',
                'is_active'      => true,
                'effective_date' => now()->toDateString(),
                'amount_mga'     => 120000, 
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
        ]);
    }
}
