<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('products')->insert([
            [
                'reference' => 'PH011',
                'name_fr' => 'MANDRAVASAROTRA',
                'name_en' => 'SARO or MANDRAVASAROTRA',
                'name_latin' => 'CINNAMOSMA FRAGRANS',
                'description_fr' => "L'Huile Essentielle Mandravasarotra est un breuvage fortifiant et purifiant, idéal pour renforcer les défenses immunitaires, c'est une plante endémique à Madagascar.",
                'description_en' => "Mandravasarotre Essential Oil is a fortifying and purifying beverage, ideal for strengthening the immune system. It is a plant endemic to Madagascar.",
                'category_id' => 1, // Huiles essentielles
                'sub_category_id' => 1,
//                'created_at' => Carbon::parse('2023-12-05 21:05:08'),
//                'updated_at' => Carbon::parse('2024-06-18 13:34:29'),
            ],
            [
                'reference' => 'PE012',
                'name_fr' => 'POIVRE ROUGE',
                'name_en' => 'RED PEPPER',
                'name_latin' => 'SCHINUS TEREBINTHIFOLIUS',
                'description_fr' => "Le poivre rouge est un type de poivre qui est récolté à pleine maturité, ce qui lui donne sa couleur rouge caractéristique. Il possède une saveur fruitée et légèrement sucrée, avec une chaleur modérée par rapport au poivre noir",
                'description_en' => "Red pepper is a type of pepper that is harvested when fully ripe, giving it its characteristic red color. It has a fruity, slightly sweet flavor, with moderate heat compared to black pepper",
                'category_id' => 2, // Épices
                'sub_category_id' => 2,
//                'created_at' => Carbon::parse('2023-12-05 21:14:01'),
//                'updated_at' => Carbon::parse('2024-05-21 11:42:58'),
            ],
            [
                'reference' => 'PE015',
                'name_fr' => 'CLOU DU GIROFLE',
                'name_en' => 'CLOVE',
                'name_latin' => 'Syzygium Aromaticum',
                'description_fr' => "Le clou de girofle est une épice obtenue à partir des boutons floraux du Giroflier de la famille des Myrtaceae et du genre Syzygium",
                'description_en' => "Clove is a spice obtained from the flower buds of the Clove tree of the Myrtaceae family and the Syzygium genus.",
                'category_id' => 2,
                'sub_category_id' => 2,
//                'created_at' => Carbon::parse('2023-12-11 12:48:14'),
//                'updated_at' => Carbon::parse('2024-06-03 16:44:55'),
            ],
            [
                'reference' => 'PH016',
                'name_fr' => 'CANELLE FEUILLE',
                'name_latin' => 'Cinnamomum Zeylanicum',
                'description_fr' => "Les feuilles de cannelle donnent une huile épicée connue pour ses propriétés purifiantes. Elle est également intéressante pour atténuer les mauvaises odeurs.",
                'name_en' => 'CINNAMON LEAF',
                'description_en' => 'Cinnamon leaves make a spicy oil known for its purifying properties. It is also useful for reducing bad odors.',
                'category_id' => 1, // Huiles essentielles
                'sub_category_id' => 1,
            ],
            [
                'reference' => 'PH021',
                'name_fr' => 'CITRIODORA',
                'name_latin' => 'Eucalyptus Citronné',
                'description_fr' => "L'huile essentielle de citriodora est l'une des huiles indispensables en aromathérapie : anti-inflammatoire, antidouleur et antifongique, elle est aussi redoutablement efficace pour se débarrasser des moustiques",
                'name_en' => 'CITRIODORA',
                'description_en' => 'Citriodora essential oil is one of the essential oils in aromatherapy: anti-inflammatory, painkiller and antifungal, it is also extremely effective in getting rid of mosquitoes.',
                'category_id' => 1,
                'sub_category_id' => 1,
            ],
            [
                'reference' => 'PH022',
                'name_fr' => 'CYPRESS',
                'name_latin' => 'Cupressus Sempervirens',
                'description_fr' => "L’huile essentielle cyprès est une arme antifatigue.",
                'name_en' => 'CYPRES',
                'description_en' => 'Cypress essential oil is an anti-fatigue weapon.',
                'category_id' => 1,
                'sub_category_id' => 1,
            ],
            [
                'reference' => 'PH023',
                'name_fr' => 'DINGADINGANA',
                'name_latin' => 'Psiadia Altissima',
                'description_fr' => "C'est une huile encore rare et très bénéfique. Elle a une odeur très agréable à diffuser",
                'name_en' => 'DINGADINGANA',
                'description_en' => 'It is still a rare and very beneficial oil. It has a very pleasant scent to diffuse.',
                'category_id' => 1,
                'sub_category_id' => 1,
            ],
            [
                'reference' => 'PH024',
                'name_fr' => 'GIROFLE',
                'name_latin' => 'Eugenia Caryophyllata',
                'description_fr' => "On utilise l’huile essentielle girofle feuilles pour des diffusions avec des huiles douces pour purifier l’air. Elle peut aider à soulager les douleurs dentaires et les maux de tête. Elle est également utilisée pour apaiser les douleurs musculaires et articulaires, améliorer la circulation sanguine et stimuler le système immunitaire.",
                'name_en' => 'CLOVE',
                'description_en' => 'We use clove leaf essential oil for diffusions with gentle oils to purify the air. It can help relieve dental pain and headaches. It is also used to soothe muscle and joint pain, improve blood circulation and stimulate the immune system.',
                'category_id' => 1,
                'sub_category_id' => 1,
            ],
            [
                'reference' => 'PH025',
                'name_fr' => 'GLOBULUS',
                'name_latin' => 'Eucalyptus Globulus',
                'description_fr' => "Apaise les voies respiratoires et purifie l’air",
                'name_en' => 'GLOBULUS',
                'description_en' => 'Soothes the respiratory tract and purifies the air',
                'category_id' => 1,
                'sub_category_id' => 1,
            ],
            [
                'reference' => 'PH026',
                'name_fr' => 'RADIATA',
                'name_latin' => 'EUCALYPTUS RADIE',
                'description_fr' => "L’huile essentielle d’Eucalyptus radié est un des meilleurs remèdes naturels pour traiter les infections respiratoires",
                'name_en' => 'RADIATA',
                'description_en' => 'Radiated Eucalyptus essential oil is one of the best natural remedies for treating respiratory infections.',
                'category_id' => 1,
                'sub_category_id' => 1,
            ],
            [
                'reference' => 'PH027',
                'name_fr' => 'RAMBIAZINA',
                'name_latin' => 'Hélichrysum Gymnocéphalum',
                'description_fr' => "L’huile essentielle Rambiazina apaise les fièvres et les rhumes.",
                'name_en' => 'RAMBIAZINA',
                'description_en' => 'Rambiazina essential oil soothes fevers and colds',
                'category_id' => 1,
                'sub_category_id' => 1,
            ],
            [
                'reference' => 'PH028',
                'name_fr' => 'RAVINTSARA FEUILLE',
                'name_latin' => 'CINNAMOMUM CAMPHORA',
                'description_fr' => "L’huile essentielle de Ravintsara possède des propriétés anti-infectieuses puissantes qui permettent de lutter contre les infections respiratoires et les rhume ou la grippe.",
                'name_en' => 'RAVINTSARA LEAF',
                'description_en' => 'Ravintsara essential oil has powerful anti-infectious properties that help fight respiratory infections and colds or flu.',
                'category_id' => 1,
                'sub_category_id' => 1,
            ],
            [
                'reference' => 'PH029',
                'name_fr' => 'YLANG YLANG',
                'name_latin' => 'CANANGA ODORATA',
                'description_fr' => "L’huile essentielle d'Ylang-ylang se distingue par son odeur, à la fois sucrée, fleurie et exotique.",
                'name_en' => 'YLANG YLANG',
                'description_en' => 'Ylang-ylang essential oil is distinguished by its smell, which is sweet, flowery and exotic',
                'category_id' => 1,
                'sub_category_id' => 1,
            ],
            [
                'reference' => 'PE030',
                'name_fr' => 'FEVES DE CACAO',
                'name_latin' => 'Théobroma cacao',
                'description_fr' => "Le cacao est une épice très appréciable. Elle est purement naturelle.",
                'name_en' => 'COCOA BEANS',
                'description_en' => 'Cocoa is a very appreciable spice. It is purely natural',
                'category_id' => 1,
                'sub_category_id' => 2,
            ],
            [
                'reference' => 'PE031',
                'name_fr' => 'VANILLE',
                'name_latin' => 'Planifolia',
                'description_fr' => "La vanille est une épice provenant de fruits d’orchidées lianescentes. Elle est une épice réputée pour ses arômes sucrés et doux",
                'name_en' => 'VANILLA',
                'description_en' => 'Vanilla is a spice coming from the fruits of lianaescent orchids. It is a spice renowned for its sweet and mild aromas',
                'category_id' => 1,
                'sub_category_id' => 2,
            ],
            [
                'reference' => 'PH032',
                'name_fr' => 'LONGOZA',
                'name_latin' => 'Aframomum Angustifolium',
                'description_fr' => "Les feuilles de Longoza donnent une essence aromatique ayant de nombreux composants actifs. Cette essence est utilisée essentiellement pour les massages relaxants avec des huiles végétales. Il est prescrit pour des personnes manque de sommeil.",
                'name_en' => 'LONGOZA',
                'description_en' => "Longoza leaves produce an aromatic essence with many active components. This essence is mainly used for relaxing massages with vegetable oils. It is prescribed for people who lack sleep.",
                'category_id' => 1,
                'sub_category_id' => 1,
            ],
            [
                'reference' => 'PH033',
                'name_fr' => 'KATRAFAY',
                'name_latin' => 'Cedrelopsis Grevei',
                'description_fr' => "L'huile essentielle de Katafray est réputée pour soulager les douleurs musculaires et articulaires mais aussi les maux de tête et de gorge.",
                'name_en' => 'KATRAFAY',
                'description_en' => "Katafray essential oil is known to relieve muscle and joint pain but also headaches and throat pain",
                'category_id' => 1,
                'sub_category_id' => 1,
            ],
            [
                'reference' => 'PH034',
                'name_fr' => 'POIVRE NOIR',
                'name_latin' => 'Piper Nigrum',
                'description_fr' => "L'huile essentielle poivre noir est utilisé comme anti-inflammatoire, aphrodisiaque et stimulant des fonctions digestives depuis toujours.",
                'name_en' => 'BLACK PEPPER',
                'description_en' => "Black pepper essential oil has always been used as an anti-inflammatory, aphrodisiac and stimulant of digestive functions.",
                'category_id' => 1,
                'sub_category_id' => 1,
            ],
            [
                'reference' => 'PH035',
                'name_fr' => 'NIAOULI',
                'name_latin' => 'Melaleuca Quinquenervia',
                'description_fr' => "L’huile essentielle de Niaouli est utilisée pour lutter contre les infections respiratoires grâce à ses propriétés anti-infectieuses, expectorantes et immunostimulantes. Il aussi beaucoup de biens faits comme protège et restaure la peau qui est cicatrisé.",
                'name_en' => 'NIAOULI',
                'description_en' => "Niaouli essential oil is used to fight respiratory infections thanks to its anti-infectious, expectorant and immunostimulating properties. It also does a lot of good like protects and restores skin that is scarred.",
                'category_id' => 1,
                'sub_category_id' => 1,
            ],
            [
                'reference' => 'PH036',
                'name_fr' => 'VETIVER',
                'name_latin' => 'Vetiveria zizanoides',
                'description_fr' => "L’huile essentielle de vétiver est reconnue pour ses propriétés relaxantes et apaisantes, elle est très utile pour dissiper les insomnies et les stress. Son odeur boisé, terreux, presque fumé fait une matière première importante en parfumerie.",
                'name_en' => 'VETIVER',
                'description_en' => "Vetiver essential oil is known for its relaxing and soothing properties, it is very useful for dispelling insomnia and stress. Its woody, earthy, almost smoky smell makes it an important raw material in perfumery.",
                'category_id' => 1,
                'sub_category_id' => 1,
            ],
            [
                'reference' => 'PE037',
                'name_fr' => 'CANNELLE',
                'name_latin' => 'Cinnamomum Verum',
                'description_fr' => "La cannelle est principalement utilisée en cuisine comme condiment et substance aromatique. Elle est une épice qui est plein de vitamines et de minéraux.",
                'name_en' => 'CINNAMON',
                'description_en' => "Cinnamon is mainly used in cooking as a condiment and aromatic substance. It is a spice that is full of vitamins and minerals.",
                'category_id' => 2,
                'sub_category_id' => 2,
            ],
            [
                'reference' => 'PE038',
                'name_fr' => 'PIMENT DE CAYENNE',
                'name_latin' => 'Capsicum frutescens',
                'description_fr' => "Le piment cayenne est utilisé pour les maux de tête, les troubles rhumatismaux, les douleurs musculaires, les maux de dents et les douleurs menstruelles.",
                'name_en' => "BIRD'S EYE CHILI",
                'description_en' => "Cayenne pepper is used for headaches, rheumatic disorders, muscle pain, toothache and menstrual pain",
                'category_id' => 2,
                'sub_category_id' => 2,
            ],
            [
                'reference' => 'PE039',
                'name_fr' => 'POIVRE NOIR',
                'name_latin' => 'Piper Nigrum',
                'description_fr' => "Le poivre noir est le plus piquant et le plus aromatique des poivres.",
                'name_en' => 'BLACK PEPPER',
                'description_en' => "Black pepper is the hottest and most aromatic of peppers.",
                'category_id' => 2,
                'sub_category_id' => 2,
            ],

            // Tu peux continuer à ajouter les autres produits ici
        ]);
    }
}
